# Generated by Django 2.2.3 on 2019-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default='', max_length=100)),
                ('movie_release_date', models.DateField(default='')),
                ('movie_duration', models.CharField(default='', max_length=100)),
                ('movie_type', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('historical fiction', 'Historical fiction'), ('horror', 'Horror'), ('philosophical', 'Philosophical'), ('political', 'Political'), ('romance', 'Romance'), ('science fiction', 'Science fiction'), ('thriller', 'Thriller'), ('western', 'Western')], max_length=50)),
                ('movie_director', models.CharField(default='', max_length=100)),
                ('movie_cast', models.TextField(default='', max_length=9000)),
                ('movie_rating', models.CharField(default='0/0', max_length=100)),
                ('movie_story', models.TextField(default='', max_length=90000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(default='', upload_to='movie images')),
            ],
            options={
                'verbose_name_plural': 'Movie Informations',
            },
        ),
    ]
