# Generated by Django 2.2.3 on 2019-09-20 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_reviewapp', '0002_movie_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_reviews',
            options={'verbose_name_plural': 'Movie Review'},
        ),
        migrations.CreateModel(
            name='comment_movie_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='0/0', max_length=100)),
                ('comment_review', models.TextField(default='', max_length=90000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_reviewapp.movie_reviews')),
            ],
            options={
                'verbose_name_plural': 'Comment Movie Review',
            },
        ),
    ]
