# Generated by Django 2.2.3 on 2019-09-24 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_reviewapp', '0003_auto_20190920_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_movie_review',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=200)),
                ('name', models.ForeignKey(default=None, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
